import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import styles from './ShopInterface.module.css';
import parchmentStyles from '../../styles/parchment.module.css';
import { ShoppingCart, X } from 'lucide-react';
const ShopInterface = ({ merchantName, merchantItems, playerItems, playerGold, onBuy, onSell, onClose, className = '' }) => {
    const [activeTab, setActiveTab] = useState('buy');
    return (_jsx("div", { className: `${styles.overlay} ${className}`, children: _jsxs("div", { className: `${styles.modal} ${parchmentStyles.panel}`, children: [_jsxs("div", { className: styles.header, children: [_jsxs("div", { className: styles.headerTitle, children: [_jsx(ShoppingCart, { size: 20, className: styles.icon }), _jsxs("h2", { className: parchmentStyles.heading, children: [merchantName, "'s Shop"] })] }), _jsx("button", { className: styles.closeButton, onClick: onClose, children: _jsx(X, { size: 20 }) })] }), _jsxs("div", { className: styles.tabs, children: [_jsx("button", { className: `${styles.tab} ${activeTab === 'buy' ? styles.activeTab : ''} ${parchmentStyles.button}`, onClick: () => setActiveTab('buy'), children: "Buy" }), _jsx("button", { className: `${styles.tab} ${activeTab === 'sell' ? styles.activeTab : ''} ${parchmentStyles.button}`, onClick: () => setActiveTab('sell'), children: "Sell" })] }), _jsx("div", { className: styles.content, children: _jsxs("div", { className: styles.gridSection, children: [_jsxs("div", { className: styles.sectionHeader, children: [_jsx("span", { children: activeTab === 'buy' ? 'Merchant Stock' : 'Your Inventory' }), _jsx("div", { className: styles.gold, children: _jsxs("span", { children: ["Current Gold: ", playerGold.gp, "g ", playerGold.sp, "s ", playerGold.cp, "c"] }) })] }), _jsx("div", { className: styles.itemList, children: (activeTab === 'buy' ? merchantItems : playerItems).map(item => (_jsxs("div", { className: styles.itemRow, children: [_jsxs("div", { className: styles.itemInfo, children: [_jsx("span", { className: styles.itemName, children: item.name }), _jsx("span", { className: styles.itemType, children: item.type })] }), _jsxs("div", { className: styles.actions, children: [_jsxs("div", { className: styles.cost, children: [item.cost.gp, "g ", item.cost.sp, "s ", item.cost.cp, "c"] }), _jsx("button", { className: `${styles.actionButton} ${parchmentStyles.button}`, onClick: () => activeTab === 'buy' ? onBuy(item.id) : onSell(item.id), children: activeTab === 'buy' ? 'Buy' : 'Sell' })] })] }, item.id))) })] }) })] }) }));
};
export default ShopInterface;
