import { PaperdollItem, EquippedSlots } from './types';

export const MOCK_ITEMS: PaperdollItem[] = [
    {
        id: 'longsword',
        instanceId: 'inst_longsword_1',
        name: 'Longsword +1',
        type: 'Weapon',
        weight: 3,
        quantity: 1,
        equipped: false,
        description: 'A finely crafted longsword with a faint magical glow along its edge. Forged by elven smiths of the Moonshae Isles.',
        damage: { dice: '1d8+1', type: 'slashing' },
        properties: ['Versatile'],
        isMagic: true,
        rarity: 'uncommon',
    },
    {
        id: 'shield_oak',
        instanceId: 'inst_shield_1',
        name: 'Shield of the Oak',
        type: 'Shield',
        weight: 6,
        quantity: 1,
        equipped: false,
        description: 'A sturdy wooden shield reinforced with iron bands. An oak tree is carved into its face.',
        acBonus: 2,
        rarity: 'common',
    },
    {
        id: 'chain_mail',
        instanceId: 'inst_chainmail_1',
        name: 'Chain Mail',
        type: 'Armor',
        weight: 55,
        quantity: 1,
        equipped: false,
        description: 'Interlocking metal rings form a mesh that covers the torso and upper legs. A staple of seasoned fighters.',
        acCalculated: '16',
        strengthReq: 13,
        stealthDisadvantage: true,
        rarity: 'common',
    },
    {
        id: 'helm_valor',
        instanceId: 'inst_helm_1',
        name: 'Helm of Valor',
        type: 'Helmet',
        weight: 3,
        quantity: 1,
        equipped: false,
        description: 'A steel helm adorned with golden wings. Grants courage to the wearer in times of darkness.',
        isMagic: true,
        rarity: 'rare',
    },
    {
        id: 'cloak_elvenkind',
        instanceId: 'inst_cloak_1',
        name: 'Cloak of Elvenkind',
        type: 'Cloak',
        weight: 1,
        quantity: 1,
        equipped: false,
        description: 'This cloak shifts color to blend with the surrounding environment. Advantage on Stealth checks.',
        isMagic: true,
        attunement: true,
        rarity: 'uncommon',
    },
    {
        id: 'amulet_health',
        instanceId: 'inst_amulet_1',
        name: 'Amulet of Health',
        type: 'Amulet',
        weight: 0.5,
        quantity: 1,
        equipped: false,
        description: 'Your Constitution score is 19 while you wear this amulet. A deep red gem pulses faintly at its center.',
        isMagic: true,
        attunement: true,
        rarity: 'rare',
    },
    {
        id: 'belt_giant',
        instanceId: 'inst_belt_1',
        name: 'Belt of Hill Giant Strength',
        type: 'Belt',
        weight: 2,
        quantity: 1,
        equipped: false,
        description: 'While wearing this belt, your Strength score changes to 21. Thick leather adorned with dwarven runes.',
        isMagic: true,
        attunement: true,
        rarity: 'rare',
    },
    {
        id: 'bracers_defense',
        instanceId: 'inst_bracers_1',
        name: 'Bracers of Defense',
        type: 'Bracers',
        weight: 1,
        quantity: 1,
        equipped: false,
        description: '+2 bonus to AC while wearing no armor and using no shield. Engraved with protective sigils.',
        acBonus: 2,
        isMagic: true,
        attunement: true,
        rarity: 'rare',
    },
    {
        id: 'gauntlets_ogre',
        instanceId: 'inst_gloves_1',
        name: 'Gauntlets of Ogre Power',
        type: 'Gloves',
        weight: 2,
        quantity: 1,
        equipped: false,
        description: 'Your Strength score is 19 while you wear these gauntlets. Crafted from darkened steel and giant hide.',
        isMagic: true,
        attunement: true,
        rarity: 'uncommon',
    },
    {
        id: 'boots_speed',
        instanceId: 'inst_boots_1',
        name: 'Boots of Speed',
        type: 'Boots',
        weight: 1,
        quantity: 1,
        equipped: false,
        description: 'Click heels together to double walking speed for 10 minutes. Leaves faint trails of light.',
        isMagic: true,
        attunement: true,
        rarity: 'rare',
    },
    {
        id: 'ring_protection',
        instanceId: 'inst_ring_1',
        name: 'Ring of Protection',
        type: 'Ring',
        weight: 0,
        quantity: 1,
        equipped: false,
        description: '+1 bonus to AC and saving throws while wearing this ring. A thin band of mithril set with a sapphire.',
        acBonus: 1,
        isMagic: true,
        attunement: true,
        rarity: 'rare',
    },
    {
        id: 'ring_resistance',
        instanceId: 'inst_ring_2',
        name: 'Ring of Fire Resistance',
        type: 'Ring',
        weight: 0,
        quantity: 1,
        equipped: false,
        description: 'Resistance to fire damage. The band is warm to the touch and bears ruby inlays.',
        isMagic: true,
        attunement: true,
        rarity: 'rare',
    },
    {
        id: 'ring_jumping',
        instanceId: 'inst_ring_3',
        name: 'Ring of Jumping',
        type: 'Ring',
        weight: 0,
        quantity: 1,
        equipped: false,
        description: 'Cast Jump on yourself at will. A silver band etched with tiny grasshoppers.',
        isMagic: true,
        attunement: true,
        rarity: 'uncommon',
    },
    {
        id: 'arrows_20',
        instanceId: 'inst_arrows_1',
        name: 'Arrows (20)',
        type: 'Ammunition',
        weight: 1,
        quantity: 20,
        equipped: false,
        description: 'A quiver of twenty standard arrows with steel broadheads.',
        rarity: 'common',
    },
    {
        id: 'shortbow',
        instanceId: 'inst_shortbow_1',
        name: 'Shortbow',
        type: 'Weapon',
        weight: 2,
        quantity: 1,
        equipped: false,
        description: 'A simple shortbow made of yew. Reliable and light.',
        damage: { dice: '1d6', type: 'piercing' },
        properties: ['Ammunition', 'Two-Handed'],
        range: { normal: 80, long: 320 },
        rarity: 'common',
    },
    {
        id: 'potion_healing',
        instanceId: 'inst_potion_1',
        name: 'Potion of Healing',
        type: 'Adventuring Gear',
        weight: 0.5,
        quantity: 3,
        equipped: false,
        description: 'A vial of red liquid that glimmers when agitated. Restores 2d4+2 hit points.',
        charges: 1,
        rarity: 'common',
    },
    {
        id: 'rope_silk',
        instanceId: 'inst_rope_1',
        name: 'Silk Rope (50 ft)',
        type: 'Adventuring Gear',
        weight: 5,
        quantity: 1,
        equipped: false,
        description: 'Fifty feet of fine silk rope. Strong enough to hold 500 pounds.',
        rarity: 'common',
    },
    {
        id: 'thieves_tools',
        instanceId: 'inst_tools_1',
        name: "Thieves' Tools",
        type: 'Tool',
        weight: 1,
        quantity: 1,
        equipped: false,
        description: 'A set of lockpicks, a small mirror, narrow-bladed scissors, and pliers.',
        rarity: 'common',
    },
];

export const MOCK_EQUIPPED: EquippedSlots = {
    head: null,
    neck: null,
    shoulders: null,
    armor: null,
    cloak: null,
    belt: null,
    bracers: null,
    gloves: null,
    legs: null,
    feet: null,
    mainHand: null,
    offHand: null,
    ammunition: null,
    leftRing1: null,
    leftRing2: null,
    leftRing3: null,
    leftRing4: null,
    leftRing5: null,
    rightRing1: null,
    rightRing2: null,
    rightRing3: null,
    rightRing4: null,
    rightRing5: null,
};

export const MOCK_GOLD = { gp: 142, sp: 37, cp: 85 };
