import React, { useState } from 'react';
import styles from './MainViewport.module.css';
import NarrativeBox from '../narrative/NarrativeBox';
import PlayerInputField from '../actions/PlayerInputField';
import InitiativeTracker from '../combat/InitiativeTracker';
import CombatLog from '../combat/CombatLog';
import DiceRoller from '../combat/DiceRoller';
import CombatActionBar from '../combat/CombatActionBar';
import LoadingOverlay from '../common/LoadingOverlay';
import TurnBanner from '../combat/TurnBanner';
import CombatOverlay from '../combat/CombatOverlay';
import CombatantStatusCard from '../combat/CombatantStatusCard';
import GameOverScreen from '../menu/GameOverScreen';
import SaveLoadModal from '../menu/SaveLoadModal';
import RestWaitModal from '../exploration/RestWaitModal';
import { useGameState } from '../../hooks/useGameState';
import { useCallback, useEffect } from 'react';

interface MainViewportProps {
    className?: string;
}

const MainViewport: React.FC<MainViewportProps> = ({ className }) => {
    const { state, processCommand, isLoading, endGame, engine, startGame, loadGame, loadLastSave, getSaveRegistry } = useGameState();
    const [showLoadModal, setShowLoadModal] = useState(false);
    const [showRestModal, setShowRestModal] = useState(false);
    const [inspectedCombatantId, setInspectedCombatantId] = useState<string | null>(null);
    const [saveSlots, setSaveSlots] = useState<any[]>([]);

    // Refresh registry when modal opens
    useEffect(() => {
        const fetchRegistry = async () => {
            if (showLoadModal && engine) {
                const registry = await getSaveRegistry();
                const slots = registry.slots.map((s: any) => ({
                    id: s.id,
                    name: s.slotName || 'Quick Save',
                    charName: s.characterName,
                    level: s.characterLevel,
                    location: s.locationSummary,
                    lastSaved: new Date(s.lastSaved).toLocaleString(),
                    playTime: `${Math.floor(s.playTimeSeconds / 60)}m`
                }));
                setSaveSlots(slots);
            }
        };
        fetchRegistry();
    }, [showLoadModal, engine, getSaveRegistry]);

    const isCombat = state?.mode === 'COMBAT';

    // Fail-safe: Ensure Rest modal closes if combat starts
    useEffect(() => {
        if (isCombat && showRestModal) {
            setShowRestModal(false);
        }
    }, [isCombat, showRestModal]);

    const handleRestCancel = useCallback(() => {
        setShowRestModal(false);
    }, []);

    const handleInspect = (id: string) => {
        setInspectedCombatantId(prev => prev === id ? null : id);
    };

    const isGameOver = state?.mode === 'GAME_OVER';

    const narrativeText = state?.lastNarrative || state?.storySummary ||
        "Welcome to your adventure. Describe your first move...";

    const locationTitle = state ?
        `${isCombat ? '[COMBAT] ' : ''}Coordinates: [${state.location.coordinates.join(', ')}]` :
        "Starting Location";

    // Placeholder actions if none generated by LLM yet
    const suggestedActions = isCombat ? [
        "Attack",
        "Dodge",
        "Use Item",
        "Exit Combat"
    ] : [
        "Look around",
        "Check gear",
        "Rest"
    ];

    const handlePlayerInput = async (input: string) => {
        if (input.toLowerCase() === 'rest') {
            setShowRestModal(true);
            return;
        }
        await processCommand(input);
    };

    const handleLoadGame = async (saveId: string) => {
        await loadGame(saveId);
        setShowLoadModal(false);
    };

    const handleLoadLastSave = async () => {
        await loadLastSave();
    };

    const handleReturnToMenu = () => {
        endGame();
    };

    const handleOpenLoadModal = () => {
        setShowLoadModal(true);
    };

    const inspectedCombatant = state?.combat?.combatants.find(c => c.id === inspectedCombatantId);
    const playerCombatant = state?.combat?.combatants.find(c => c.isPlayer);

    return (
        <main className={`${styles.viewport} ${className} ${isCombat ? styles.combatMode : ''}`}>
            {/* Loading Overlay */}
            {isLoading && <LoadingOverlay message="Loading..." />}

            {isGameOver && (
                <GameOverScreen
                    onLoadLastSave={handleLoadLastSave}
                    onReturnToMenu={handleReturnToMenu}
                    onLoadGame={handleOpenLoadModal}
                />
            )}

            {showLoadModal && (
                <SaveLoadModal
                    mode="load"
                    slots={saveSlots}
                    onAction={handleLoadGame}
                    onDelete={() => { }} // No-op for now
                    onClose={() => setShowLoadModal(false)}
                />
            )}

            {showRestModal && (
                <RestWaitModal
                    engine={engine}
                    onCancel={handleRestCancel}
                />
            )}

            {isCombat && state.combat && (
                <>
                    <TurnBanner />
                    <CombatOverlay events={state.combat.events} />
                    <div className={styles.combatTopBar}>
                        <InitiativeTracker
                            combatants={state.combat.combatants}
                            currentTurnId={state.combat.combatants[state.combat.currentTurnIndex]?.id || ''}
                            selectedTargetId={state.combat.selectedTargetId}
                            onSelectTarget={async (id) => await processCommand(`/target ${id}`)}
                            onInspect={handleInspect}
                        />
                    </div>

                    {inspectedCombatant && playerCombatant && (
                        <div className={styles.inspectorContainer}>
                            <CombatantStatusCard
                                combatant={inspectedCombatant}
                                playerPos={playerCombatant.position}
                                cover="None" // TODO: Calculate from engine/grid
                                lighting="Bright" // TODO: Calculate from weather/time
                                onClose={() => setInspectedCombatantId(null)}
                            />
                        </div>
                    )}
                </>
            )}

            <div className={styles.centerArea}>
                <div className={styles.narrativeContainer}>
                    <NarrativeBox
                        title={locationTitle}
                        text={narrativeText}
                    />
                </div>

                {isCombat && state.combat && (
                    <div className={styles.combatSidePanel}>
                        <CombatLog
                            logs={state.combat.logs}
                            className={styles.combatLog}
                        />
                        <DiceRoller
                            className={styles.combatDice}
                            sides={20}
                            result={state.combat.lastRoll}
                            isRolling={isLoading} // Simple approximation
                        />
                    </div>
                )}
            </div>

            <div className={styles.actionBar}>
                {isCombat ? (
                    <CombatActionBar />
                ) : (
                    <PlayerInputField
                        suggestedActions={suggestedActions}
                        onSubmit={handlePlayerInput}
                    />
                )}
            </div>
        </main>
    );
};

export default MainViewport;
