import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import styles from './MainViewport.module.css';
import NarrativeBox from '../narrative/NarrativeBox';
import PlayerInputField from '../actions/PlayerInputField';
import { useGameState } from '../../hooks/useGameState';
const MainViewport = ({ className }) => {
    const { state, processCommand } = useGameState();
    const narrativeText = state?.storySummary ||
        "Welcome to your adventure. Describe your first move...";
    const locationTitle = state ?
        `Coordinates: [${state.location.coordinates.join(', ')}]` :
        "Starting Location";
    // Placeholder actions if none generated by LLM yet
    const suggestedActions = [
        "Look around",
        "Check gear",
        "Move North",
        "Rest"
    ];
    const handlePlayerInput = (input) => {
        processCommand(input);
    };
    return (_jsxs("main", { className: `${styles.viewport} ${className}`, children: [_jsx("div", { className: styles.narrativeContainer, children: _jsx(NarrativeBox, { title: locationTitle, text: narrativeText }) }), _jsx("div", { className: styles.actionBar, children: _jsx(PlayerInputField, { suggestedActions: suggestedActions, onSubmit: handlePlayerInput }) })] }));
};
export default MainViewport;
