import React, { useState } from 'react';
import styles from './MainViewport.module.css';
import NarrativeBox from '../narrative/NarrativeBox';
import PlayerInputField from '../actions/PlayerInputField';
import InitiativeTracker from '../combat/InitiativeTracker';
import CombatLog from '../combat/CombatLog';
import DiceRoller from '../combat/DiceRoller';
import CombatActionBar from '../combat/CombatActionBar';
import LoadingOverlay from '../common/LoadingOverlay';
import TurnBanner from '../combat/TurnBanner';
import CombatOverlay from '../combat/CombatOverlay';

interface MainViewportProps {
    className?: string;
}

import { useGameState } from '../../hooks/useGameState';

const MainViewport: React.FC<MainViewportProps> = ({ className }) => {
    const { state, processCommand, isLoading } = useGameState();

    const isCombat = state?.mode === 'COMBAT';

    const narrativeText = state?.lastNarrative || state?.storySummary ||
        "Welcome to your adventure. Describe your first move...";

    const locationTitle = state ?
        `${isCombat ? '[COMBAT] ' : ''}Coordinates: [${state.location.coordinates.join(', ')}]` :
        "Starting Location";

    // Placeholder actions if none generated by LLM yet
    const suggestedActions = isCombat ? [
        "Attack",
        "Dodge",
        "Use Item",
        "Exit Combat"
    ] : [
        "Look around",
        "Check gear",
        "Move North",
        "Rest"
    ];

    const handlePlayerInput = (input: string) => {
        processCommand(input);
    };

    return (
        <main className={`${styles.viewport} ${className} ${isCombat ? styles.combatMode : ''}`}>
            {/* Loading Overlay */}
            {isLoading && <LoadingOverlay message="Loading..." />}

            {isCombat && state.combat && (
                <>
                    <TurnBanner />
                    <CombatOverlay events={state.combat.events} />
                    <div className={styles.combatTopBar}>
                        <InitiativeTracker
                            combatants={state.combat.combatants}
                            currentTurnId={state.combat.combatants[state.combat.currentTurnIndex]?.id || ''}
                            selectedTargetId={state.combat.selectedTargetId}
                            onSelectTarget={(id) => processCommand(`/target ${id}`)}
                        />
                    </div>
                </>
            )}

            <div className={styles.centerArea}>
                <div className={styles.narrativeContainer}>
                    <NarrativeBox
                        title={locationTitle}
                        text={narrativeText}
                    />
                </div>

                {isCombat && state.combat && (
                    <div className={styles.combatSidePanel}>
                        <CombatLog
                            logs={state.combat.logs}
                            className={styles.combatLog}
                        />
                        <DiceRoller
                            className={styles.combatDice}
                            sides={20}
                            result={state.combat.lastRoll}
                            isRolling={isLoading} // Simple approximation
                        />
                    </div>
                )}
            </div>

            <div className={styles.actionBar}>
                {isCombat ? (
                    <CombatActionBar />
                ) : (
                    <PlayerInputField
                        suggestedActions={suggestedActions}
                        onSubmit={handlePlayerInput}
                    />
                )}
            </div>
        </main>
    );
};

export default MainViewport;
