import fs from 'fs';
import path from 'path';

// SRD Spell Mapping (Synthesized from 5thsrd.org)
const SRD_MAPPING = {
    "Acid Splash": ["Sorcerer", "Wizard"],
    "Aid": ["Cleric", "Paladin"],
    "Alarm": ["Ranger", "Wizard"],
    "Alter Self": ["Sorcerer", "Wizard"],
    "Animal Friendship": ["Bard", "Druid", "Ranger"],
    "Animal Messenger": ["Bard", "Druid", "Ranger"],
    "Animal Shapes": ["Druid"],
    "Animate Dead": ["Cleric", "Wizard"],
    "Animate Objects": ["Bard", "Sorcerer", "Wizard"],
    "Antimagic Field": ["Cleric", "Wizard"],
    "Antipathy/Sympathy": ["Druid", "Wizard"],
    "Arcane Eye": ["Wizard"],
    "Arcane Hand": ["Wizard"],
    "Arcane Lock": ["Wizard"],
    "Arcanist's Magic Aura": ["Wizard"],
    "Armor of Agathys": ["Warlock"],
    "Arms of Hadar": ["Warlock"],
    "Astral Projection": ["Cleric", "Warlock", "Wizard"],
    "Augury": ["Cleric"],
    "Aura of Life": ["Paladin"],
    "Aura of Purity": ["Paladin"],
    "Aura of Vitality": ["Paladin"],
    "Awaken": ["Bard", "Druid"],
    "Bane": ["Bard", "Cleric"],
    "Banishment": ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    "Barkskin": ["Druid", "Ranger"],
    "Beacon of Hope": ["Cleric"],
    "Beast Sense": ["Druid", "Ranger"],
    "Bestow Curse": ["Bard", "Cleric", "Wizard"],
    "Black Tentacles": ["Wizard"],
    "Blade Barrier": ["Cleric"],
    "Bless": ["Cleric", "Paladin"],
    "Blight": ["Druid", "Sorcerer", "Warlock", "Wizard"],
    "Blindness/Deafness": ["Bard", "Cleric", "Sorcerer", "Wizard"],
    "Blink": ["Sorcerer", "Wizard"],
    "Blur": ["Sorcerer", "Wizard"],
    "Branding Smite": ["Paladin"],
    "Burning Hands": ["Sorcerer", "Wizard"],
    "Call Lightning": ["Druid"],
    "Calm Emotions": ["Bard", "Cleric"],
    "Chain Lightning": ["Sorcerer", "Wizard"],
    "Charm Person": ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
    "Chill Touch": ["Sorcerer", "Warlock", "Wizard"],
    "Circle of Death": ["Sorcerer", "Warlock", "Wizard"],
    "Clairvoyance": ["Bard", "Cleric", "Sorcerer", "Wizard"],
    "Clone": ["Wizard"],
    "Cloudkill": ["Sorcerer", "Wizard"],
    "Color Spray": ["Sorcerer", "Wizard"],
    "Command": ["Cleric", "Paladin"],
    "Commune": ["Cleric"],
    "Commune with Nature": ["Druid", "Ranger"],
    "Compulsion": ["Bard"],
    "Comprehend Languages": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Cone of Cold": ["Sorcerer", "Wizard"],
    "Confusion": ["Bard", "Druid", "Sorcerer", "Wizard"],
    "Conjure Animals": ["Druid", "Ranger"],
    "Conjure Celestial": ["Cleric"],
    "Conjure Elemental": ["Druid", "Wizard"],
    "Conjure Fey": ["Druid", "Warlock"],
    "Conjure Minor Elementals": ["Druid", "Wizard"],
    "Conjure Woodland Beings": ["Druid", "Ranger"],
    "Contact Other Plane": ["Warlock", "Wizard"],
    "Contagion": ["Cleric", "Druid"],
    "Contingency": ["Wizard"],
    "Continual Flame": ["Cleric", "Wizard"],
    "Control Water": ["Cleric", "Druid", "Wizard"],
    "Control Weather": ["Cleric", "Druid", "Wizard"],
    "Counterspell": ["Sorcerer", "Warlock", "Wizard"],
    "Create Food and Water": ["Cleric", "Paladin"],
    "Create or Destroy Water": ["Cleric", "Druid"],
    "Create Undead": ["Cleric", "Warlock", "Wizard"],
    "Creation": ["Sorcerer", "Wizard"],
    "Cure Wounds": ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    "Dancing Lights": ["Bard", "Sorcerer", "Wizard"],
    "Darkness": ["Sorcerer", "Warlock", "Wizard"],
    "Darkvision": ["Druid", "Ranger", "Sorcerer", "Wizard"],
    "Daylight": ["Cleric", "Druid", "Paladin", "Ranger", "Sorcerer"],
    "Death Ward": ["Cleric", "Paladin"],
    "Delayed Blast Fireball": ["Sorcerer", "Wizard"],
    "Demiplane": ["Warlock", "Wizard"],
    "Detect Evil and Good": ["Cleric", "Paladin"],
    "Detect Magic": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
    "Detect Poison and Disease": ["Cleric", "Druid", "Paladin", "Ranger"],
    "Detect Thoughts": ["Bard", "Sorcerer", "Wizard"],
    "Dimension Door": ["Bard", "Warlock", "Wizard"],
    "Disguise Self": ["Bard", "Sorcerer", "Wizard"],
    "Disintegrate": ["Sorcerer", "Wizard"],
    "Dispel Evil and Good": ["Cleric", "Paladin"],
    "Dispel Magic": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Warlock", "Wizard"],
    "Divination": ["Cleric"],
    "Divine Favor": ["Paladin"],
    "Divine Word": ["Cleric"],
    "Dominate Beast": ["Druid", "Sorcerer"],
    "Dominate Monster": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Dominate Person": ["Bard", "Sorcerer", "Wizard"],
    "Dream": ["Bard", "Warlock", "Wizard"],
    "Druidcraft": ["Druid"],
    "Earthquake": ["Cleric", "Druid", "Sorcerer"],
    "Eldritch Blast": ["Warlock"],
    "Enhance Ability": ["Bard", "Cleric", "Druid", "Sorcerer"],
    "Enlarge/Reduce": ["Sorcerer", "Wizard"],
    "Entangle": ["Druid"],
    "Enthrall": ["Bard", "Warlock"],
    "Etherealness": ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
    "Expeditious Retreat": ["Sorcerer", "Warlock", "Wizard"],
    "Eyebite": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Fabricate": ["Wizard"],
    "Faerie Fire": ["Bard", "Druid"],
    "Faithful Hound": ["Wizard"],
    "False Life": ["Sorcerer", "Wizard"],
    "Fear": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Feather Fall": ["Bard", "Sorcerer", "Wizard"],
    "Feeblemind": ["Bard", "Druid", "Warlock", "Wizard"],
    "Find Familiar": ["Wizard"],
    "Find Steed": ["Paladin"],
    "Find the Path": ["Bard", "Cleric", "Druid"],
    "Find Traps": ["Cleric", "Druid", "Ranger"],
    "Finger of Death": ["Sorcerer", "Warlock", "Wizard"],
    "Fireball": ["Sorcerer", "Wizard"],
    "Fire Bolt": ["Sorcerer", "Wizard"],
    "Fire Shield": ["Wizard"],
    "Fire Storm": ["Cleric", "Druid", "Sorcerer"],
    "Flame Blade": ["Druid"],
    "Flame Strike": ["Cleric"],
    "Flaming Sphere": ["Druid", "Wizard"],
    "Flesh to Stone": ["Warlock", "Wizard"],
    "Floating Disk": ["Wizard"],
    "Fly": ["Sorcerer", "Warlock", "Wizard"],
    "Fog Cloud": ["Druid", "Ranger", "Sorcerer", "Wizard"],
    "Forbiddance": ["Cleric"],
    "Forcecage": ["Warlock", "Wizard"],
    "Foresight": ["Bard", "Druid", "Warlock", "Wizard"],
    "Freedom of Movement": ["Bard", "Cleric", "Druid", "Ranger"],
    "Freezing Sphere": ["Wizard"],
    "Gaseous Form": ["Sorcerer", "Warlock", "Wizard"],
    "Gate": ["Cleric", "Warlock", "Wizard"],
    "Geas": ["Bard", "Cleric", "Druid", "Paladin", "Wizard"],
    "Gentle Repose": ["Cleric", "Wizard"],
    "Giant Insect": ["Druid"],
    "Glibness": ["Bard", "Warlock"],
    "Globe of Invulnerability": ["Sorcerer", "Wizard"],
    "Glyph of Warding": ["Bard", "Cleric", "Wizard"],
    "Goodberry": ["Druid", "Ranger"],
    "Grease": ["Wizard"],
    "Greater Invisibility": ["Bard", "Sorcerer", "Wizard"],
    "Greater Restoration": ["Bard", "Cleric", "Druid"],
    "Guardian of Faith": ["Cleric"],
    "Guards and Wards": ["Bard", "Wizard"],
    "Guidance": ["Cleric", "Druid"],
    "Guiding Bolt": ["Cleric"],
    "Gust of Wind": ["Druid", "Sorcerer", "Wizard"],
    "Hallow": ["Cleric"],
    "Hallucinatory Terrain": ["Bard", "Druid", "Warlock", "Wizard"],
    "Harm": ["Cleric"],
    "Haste": ["Sorcerer", "Wizard"],
    "Heal": ["Cleric", "Druid"],
    "Healing Word": ["Bard", "Cleric", "Druid"],
    "Heat Metal": ["Bard", "Druid"],
    "Hellish Rebuke": ["Warlock"],
    "Heroes' Feast": ["Cleric", "Druid"],
    "Heroism": ["Bard", "Paladin"],
    "Hex": ["Warlock"],
    "Hideous Laughter": ["Bard", "Wizard"],
    "Hold Monster": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Hold Person": ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
    "Holy Aura": ["Cleric"],
    "Hunter's Mark": ["Ranger"],
    "Hypnotic Pattern": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Ice Storm": ["Druid", "Sorcerer", "Wizard"],
    "Identify": ["Bard", "Wizard"],
    "Illusory Script": ["Bard", "Warlock", "Wizard"],
    "Imprisonment": ["Warlock", "Wizard"],
    "Incendiary Cloud": ["Sorcerer", "Wizard"],
    "Inflict Wounds": ["Cleric"],
    "Insect Plague": ["Cleric", "Druid", "Sorcerer"],
    "Instant Summons": ["Wizard"],
    "Invisibility": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Irresistible Dance": ["Bard", "Wizard"],
    "Jump": ["Druid", "Ranger", "Sorcerer", "Wizard"],
    "Knock": ["Bard", "Sorcerer", "Wizard"],
    "Legend Lore": ["Bard", "Cleric", "Wizard"],
    "Lesser Restoration": ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    "Levitate": ["Sorcerer", "Wizard"],
    "Light": ["Bard", "Cleric", "Sorcerer", "Wizard"],
    "Lightning Bolt": ["Sorcerer", "Wizard"],
    "Locate Animals or Plants": ["Bard", "Druid", "Ranger"],
    "Locate Creature": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"],
    "Locate Object": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"],
    "Longstrider": ["Bard", "Druid", "Ranger", "Wizard"],
    "Mage Armor": ["Sorcerer", "Wizard"],
    "Mage Hand": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Magic Circle": ["Cleric", "Paladin", "Warlock", "Wizard"],
    "Magic Jar": ["Wizard"],
    "Magic Missile": ["Sorcerer", "Wizard"],
    "Magic Mouth": ["Bard", "Wizard"],
    "Magic Weapon": ["Paladin", "Wizard"],
    "Magnificent Mansion": ["Wizard"],
    "Major Image": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Mass Cure Wounds": ["Bard", "Cleric", "Druid"],
    "Mass Heal": ["Cleric"],
    "Mass Healing Word": ["Cleric"],
    "Mass Suggestion": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Maze": ["Wizard"],
    "Meld into Stone": ["Cleric", "Druid"],
    "Mending": ["Bard", "Cleric", "Druid", "Sorcerer", "Wizard"],
    "Message": ["Bard", "Sorcerer", "Wizard"],
    "Meteor Swarm": ["Sorcerer", "Wizard"],
    "Mind Blank": ["Bard", "Wizard"],
    "Minor Illusion": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Mirage Arcane": ["Bard", "Druid", "Wizard"],
    "Mirror Image": ["Sorcerer", "Warlock", "Wizard"],
    "Mislead": ["Bard", "Wizard"],
    "Misty Step": ["Sorcerer", "Warlock", "Wizard"],
    "Modify Memory": ["Bard", "Wizard"],
    "Moonbeam": ["Druid"],
    "Move Earth": ["Druid", "Sorcerer", "Wizard"],
    "Nondetection": ["Bard", "Ranger", "Wizard"],
    "Passwall": ["Wizard"],
    "Pass without Trace": ["Druid", "Ranger"],
    "Phantasmal Killer": ["Wizard"],
    "Phantom Steed": ["Wizard"],
    "Planar Binding": ["Bard", "Cleric", "Druid", "Wizard"],
    "Planar Ally": ["Cleric"],
    "Plane Shift": ["Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
    "Plant Growth": ["Bard", "Druid", "Ranger"],
    "Poison Spray": ["Druid", "Sorcerer", "Warlock", "Wizard"],
    "Polymorph": ["Bard", "Druid", "Sorcerer", "Wizard"],
    "Power Word Kill": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Power Word Stun": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Prayer of Healing": ["Cleric"],
    "Prestidigitation": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Prismatic Spray": ["Sorcerer", "Wizard"],
    "Prismatic Wall": ["Wizard"],
    "Private Sanctum": ["Wizard"],
    "Produce Flame": ["Druid"],
    "Programmed Illusion": ["Wizard"],
    "Project Image": ["Bard", "Wizard"],
    "Protection from Energy": ["Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"],
    "Protection from Evil and Good": ["Cleric", "Paladin", "Warlock", "Wizard"],
    "Protection from Poison": ["Cleric", "Druid", "Paladin", "Ranger"],
    "Purify Food and Drink": ["Cleric", "Druid", "Paladin"],
    "Raise Dead": ["Bard", "Cleric", "Paladin"],
    "Ray of Enfeeblement": ["Warlock", "Wizard"],
    "Ray of Frost": ["Sorcerer", "Wizard"],
    "Regenerate": ["Bard", "Cleric", "Druid"],
    "Reincarnate": ["Druid"],
    "Remove Curse": ["Bard", "Cleric", "Paladin", "Warlock", "Wizard"],
    "Resilient Sphere": ["Wizard"],
    "Resistance": ["Cleric", "Druid"],
    "Resurrection": ["Bard", "Cleric"],
    "Reverse Gravity": ["Druid", "Sorcerer", "Wizard"],
    "Revivify": ["Cleric", "Paladin"],
    "Rope Trick": ["Wizard"],
    "Sacred Flame": ["Cleric"],
    "Sanctuary": ["Cleric", "Paladin"],
    "Scorching Ray": ["Sorcerer", "Wizard"],
    "Scrying": ["Bard", "Cleric", "Druid", "Warlock", "Wizard"],
    "Secret Chest": ["Wizard"],
    "See Invisibility": ["Bard", "Sorcerer", "Wizard"],
    "Seeming": ["Bard", "Wizard"],
    "Sending": ["Bard", "Cleric", "Wizard"],
    "Sequester": ["Wizard"],
    "Shapechange": ["Druid", "Wizard"],
    "Shatter": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Shield": ["Sorcerer", "Wizard"],
    "Shield of Faith": ["Cleric", "Paladin"],
    "Shillelagh": ["Druid"],
    "Shocking Grasp": ["Sorcerer", "Wizard"],
    "Silence": ["Bard", "Cleric", "Ranger"],
    "Silent Image": ["Bard", "Sorcerer", "Wizard"],
    "Simulacrum": ["Wizard"],
    "Sleep": ["Bard", "Sorcerer", "Wizard"],
    "Sleet Storm": ["Druid", "Sorcerer", "Wizard"],
    "Slow": ["Sorcerer", "Wizard"],
    "Speak with Animals": ["Bard", "Druid", "Ranger"],
    "Speak with Dead": ["Bard", "Cleric"],
    "Speak with Plants": ["Bard", "Druid", "Ranger"],
    "Spare the Dying": ["Cleric"],
    "Spider Climb": ["Sorcerer", "Warlock", "Wizard"],
    "Spike Growth": ["Druid", "Ranger"],
    "Spirit Guardians": ["Cleric"],
    "Spiritual Weapon": ["Cleric"],
    "Stinking Cloud": ["Bard", "Wizard"],
    "Stone Shape": ["Cleric", "Druid", "Wizard"],
    "Stoneskin": ["Druid", "Ranger", "Sorcerer", "Wizard"],
    "Storm of Vengeance": ["Druid"],
    "Suggestion": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Sunbeam": ["Cleric", "Druid", "Sorcerer", "Wizard"],
    "Sunburst": ["Cleric", "Druid", "Sorcerer", "Wizard"],
    "Swift Quiver": ["Ranger"],
    "Symbol": ["Cleric", "Wizard"],
    "Telekinesis": ["Sorcerer", "Wizard"],
    "Telepathic Bond": ["Wizard"],
    "Teleport": ["Bard", "Sorcerer", "Wizard"],
    "Teleportation Circle": ["Bard", "Wizard"],
    "Thaumaturgy": ["Cleric"],
    "Thunderwave": ["Bard", "Druid", "Sorcerer", "Wizard"],
    "Time Stop": ["Sorcerer", "Wizard"],
    "Tiny Hut": ["Bard", "Wizard"],
    "Tongues": ["Bard", "Cleric", "Warlock", "Wizard"],
    "Transport via Plants": ["Druid"],
    "Tree Stride": ["Druid", "Ranger"],
    "True Polymorph": ["Bard", "Warlock", "Wizard"],
    "True Resurrection": ["Cleric", "Druid"],
    "True Seeing": ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
    "True Strike": ["Bard", "Sorcerer", "Warlock", "Wizard"],
    "Unseen Servant": ["Bard", "Warlock", "Wizard"],
    "Vampiric Touch": ["Warlock", "Wizard"],
    "Vicious Mockery": ["Bard"],
    "Wall of Fire": ["Druid", "Sorcerer", "Wizard"],
    "Wall of Force": ["Wizard"],
    "Wall of Ice": ["Wizard"],
    "Wall of Stone": ["Druid", "Wizard"],
    "Wall of Thorns": ["Druid"],
    "Warding Bond": ["Cleric"],
    "Water Breathing": ["Druid", "Ranger", "Sorcerer", "Wizard"],
    "Water Walk": ["Cleric", "Druid", "Ranger"],
    "Web": ["Sorcerer", "Wizard"],
    "Weird": ["Wizard"],
    "Wind Walk": ["Druid"],
    "Wind Wall": ["Druid", "Ranger"],
    "Wish": ["Sorcerer", "Wizard"],
    "Witch Bolt": ["Sorcerer", "Warlock", "Wizard"],
    "Word of Recall": ["Cleric"],
    "Zone of Truth": ["Bard", "Cleric", "Paladin"]
};

const SPELL_DIR = path.resolve('data/spell');

async function cleanSpells() {
    const files = fs.readdirSync(SPELL_DIR);
    console.log(`Scanning ${files.length} spell files...`);

    let updatedCount = 0;
    let missingCount = 0;

    for (const file of files) {
        if (!file.endsWith('.json')) continue;

        const filePath = path.join(SPELL_DIR, file);
        const content = fs.readFileSync(filePath, 'utf8');
        const spell = JSON.parse(content);

        const srdClasses = SRD_MAPPING[spell.name];
        if (srdClasses) {
            spell.classes = srdClasses;
            fs.writeFileSync(filePath, JSON.stringify(spell, null, 2));
            updatedCount++;
        } else {
            console.warn(`Warning: Spell "${spell.name}" not found in SRD mapping. Skipping.`);
            missingCount++;
        }
    }

    console.log(`Cleanup complete!`);
    console.log(`Updated: ${updatedCount}`);
    console.log(`Missing from mapping: ${missingCount}`);
}

cleanSpells();
